Add listeners to correctly loads projects in total offline mode
asfoury/projmag pull request #141
Opened 2021-04-23 18:27 UTC by arnauds5

Add listeners to correctly loads projects in total offline mode.

2021-04-26 15:49 UTC, kaourintin approved these changes
The bug seems to be fixed on  my machine.

2021-04-29 19:37 UTC, PaulCoral requested changes
Won't compile, see comment

2021-04-29 19:37 UTC, PaulCoral commented on app/src/main/java/com/sdp13epfl2021/projmag/adapter/ProjectAdapter.kt
> -import android.content.Context
Won't compile as Context is not imported, and it is used in the constructor

2021-04-29 20:24 UTC, PaulCoral approved these changes
Hard to test well on my emulator, but it worked without issue
Fine for me

2021-04-29 20:25 UTC, merged