role works when you have already signed
asfoury/projmag pull request #171
Opened 2021-05-03 13:20 UTC by giogio21

2021-05-03 15:52 UTC, arnauds5 requested changes
When the app starts, the isProfessor is not loaded correctly (is always true now).
You could use something like this in MainActivity for example : 
```
UserTypeChoice.isProfessor = getSharedPreferences(userTypeChoicePrefs, Context.MODE_PRIVATE)
            .getBoolean(isProfessorPref, isProfessorDefaultValue)
```

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/SignInActivity.kt
> +                            val savedTypeChoice :String = "userTypeChoicePrefs"
Using a constant string for this would be better.

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/UserTypeChoice.kt
> +        val savedTypeChoice :String = "userTypeChoicePrefs"
the same comment

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/SignInActivity.kt
> +                            UserTypeChoice.isProfessor = settings.getBoolean("isProfessor",true)
the same comment

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/UserTypeChoice.kt
> +            editor.putBoolean("isProfessor",true)
the same comment

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/UserTypeChoice.kt
> +            editor.putBoolean("isProfessor",false)
the same comment

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/SignInActivity.kt
> +                            val settings = getSharedPreferences(savedTypeChoice, 0)
Using a magic number (0) is more difficult to understand than this.
```suggestion
                            val settings = getSharedPreferences(savedTypeChoice, Context.MODE_PRIVATE)
```

2021-05-03 15:52 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/UserTypeChoice.kt
> +        val settings = getSharedPreferences(savedTypeChoice, 0)
```suggestion
        val settings = getSharedPreferences(savedTypeChoice, Context.MODE_PRIVATE)
```

2021-05-03 18:26 UTC, arnauds5 commented on app/src/main/java/com/sdp13epfl2021/projmag/activities/SignInActivity.kt
> +                            UserTypeChoice.isProfessor = settings.getBoolean(UserTypeChoice.isUserProf,true)
The isProfessor should already be initialized by the code in MainActivity.
Maybe this code can be removed

2021-05-03 22:02 UTC, arnauds5 approved these changes
Looks good to me

2021-05-04 12:19 UTC, lpatel99 approved these changes
All good!

2021-05-04 12:19 UTC, merged